[package]
name = "many_tasks"
version = "0.1.0"
edition = "2018"


[dependencies]
druid = { version = "0.7.0", features = ["im"] }
im = { version = "*", features = ["proptest", "serde"] }

serde_json = "1.0.78"
serde = { version = "1.0.136", features = ["derive"] }